export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const MY_ORDERS_REQUEST = "MY_ORDERS_REQUEST";
export const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS";
export const MY_ORDERS_FAIL = "MY_ORDERS_FAIL";

export const ADMIN_ALL_ORDERS_REQUEST = "ADMIN_ALL_ORDERS_REQUEST";
export const ADMIN_ALL_ORDERS_SUCCESS = "ADMIN_ALL_ORDERS_SUCCESS";
export const ADMIN_ALL_ORDERS_FAIL = "ADMIN_ALL_ORDERS_FAIL";

export const ADMIN_DELETE_ORDER_REQUEST = "ADMIN_DELETE_ORDER_REQUEST";
export const ADMIN_DELETE_ORDER_SUCCESS = "ADMIN_DELETE_ORDER_SUCCESS";
export const ADMIN_DELETE_ORDER_FAIL = "ADMIN_DELETE_ORDER_FAIL";

export const ADMIN_ORDER_DETAILS_REQUEST = "ADMIN_ORDER_DETAILS_REQUEST";
export const ADMIN_ORDER_DETAILS_SUCCESS = "ADMIN_ORDER_DETAILS_SUCCESS";
export const ADMIN_ORDER_DETAILS_FAIL = "ADMIN_ORDER_DETAILS_FAIL";