export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCTS2_REQUEST = "GET_PRODUCTS2_REQUEST";
export const GET_PRODUCTS2_SUCCESS = "GET_PRODUCTS2_SUCCESS";
export const GET_PRODUCTS2_FAIL = "GET_PRODUCTS2_FAIL";

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL";
export const GET_PRODUCT_DETAILS_RESET = "GET_PRODUCT_DETAILS_RESET";

export const ADMIN_GET_PRODUCT_REQUEST = "ADMIN_GET_PRODUCT_REQUEST";
export const ADMIN_GET_PRODUCT_SUCCESS = "ADMIN_GET_PRODUCT_SUCCESS";
export const ADMIN_GET_PRODUCT_FAIL = "ADMIN_GET_PRODUCT_FAIL";

export const ADMIN_DELETE_PRODUCT_REQUEST = "ADMIN_DELETE_PRODUCT_REQUEST";
export const ADMIN_DELETE_PRODUCT_SUCCESS = "ADMIN_DELETE_PRODUCT_SUCCESS";
export const ADMIN_DELETE_PRODUCT_RESET = "ADMIN_DELETE_PRODUCT_RESET";
export const ADMIN_DELETE_PRODUCT_FAIL = "ADMIN_DELETE_PRODUCT_FAIL";
